# yaml 配置
version: '3'

# 该 Compose 文件定义了两个服务：web 和 redis。
services:
  # 该 web 服务使用从 Dockerfile 当前目录中构建的镜像。然后，它将容器和主机绑定到暴露的端口 5000。此示例服务使用 Flask Web 服务器的默认端口 5000 
  web:
    build: .
    ports:
     - "5000:5000"
  # 该 redis 服务使用 Docker Hub 的公共 Redis 映像
  redis:
    image: "redis:alpine"
