application:
  name: prod环境 @artifactId@
  version: prod环境 @version@

developer:
  name: prod环境 Jerry
  website: prod环境 http://baidu.com/
  qq: prod环境 1234567812314
  phone-number: prod环境 1242141245125
